'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Data

Namespace SyncMobile
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SyncMobile.SyncMobileSoap")>  _
    Public Interface SyncMobileSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FineSync", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function FineSync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REL As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FineSync", ReplyAction:="*")>  _
        Function FineSyncAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InizioSync", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function InizioSync(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InizioSync", ReplyAction:="*")>  _
        Function InizioSyncAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPRichiestaAbilitazione", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPRichiestaAbilitazione(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPRichiestaAbilitazione", ReplyAction:="*")>  _
        Function APPRichiestaAbilitazioneAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetUtenti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetUtenti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetUtenti", ReplyAction:="*")>  _
        Function APPGetUtentiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClienti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiniClienti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClienti", ReplyAction:="*")>  _
        Function APPGetRapportiniClientiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClientiSedi", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiniClientiSedi(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClientiSedi", ReplyAction:="*")>  _
        Function APPGetRapportiniClientiSediAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClientiSediSpese", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiniClientiSediSpese(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClientiSediSpese", ReplyAction:="*")>  _
        Function APPGetRapportiniClientiSediSpeseAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClientiSediSoggetti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiniClientiSediSoggetti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniClientiSediSoggetti", ReplyAction:="*")>  _
        Function APPGetRapportiniClientiSediSoggettiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniNoteSpeseTipi", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiniNoteSpeseTipi(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniNoteSpeseTipi", ReplyAction:="*")>  _
        Function APPGetRapportiniNoteSpeseTipiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniCommesse", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiniCommesse(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiniCommesse", ReplyAction:="*")>  _
        Function APPGetRapportiniCommesseAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapporti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapporti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapporti", ReplyAction:="*")>  _
        Function APPGetRapportiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutRapporti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPPutRapporti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutRapporti", ReplyAction:="*")>  _
        Function APPPutRapportiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutRapportiFromDomino", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPPutRapportiFromDomino(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutRapportiFromDomino", ReplyAction:="*")>  _
        Function APPPutRapportiFromDominoAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetAutorizzazioniTelegram", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetAutorizzazioniTelegram(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetAutorizzazioniTelegram", ReplyAction:="*")>  _
        Function APPGetAutorizzazioniTelegramAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutRapportiFromTelegram", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPPutRapportiFromTelegram(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutRapportiFromTelegram", ReplyAction:="*")>  _
        Function APPPutRapportiFromTelegramAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiSpese", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetRapportiSpese(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetRapportiSpese", ReplyAction:="*")>  _
        Function APPGetRapportiSpeseAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UploadFirmaSoggetto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function UploadFirmaSoggetto(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UploadFirmaSoggetto", ReplyAction:="*")>  _
        Function UploadFirmaSoggettoAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDominoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub GetDominoData(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDominoData", ReplyAction:="*")>  _
        Function GetDominoDataAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDominoDataQuery", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetDominoDataQuery(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDominoDataQuery", ReplyAction:="*")>  _
        Function GetDominoDataQueryAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetBARCODEFamiglie", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetBARCODEFamiglie(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetBARCODEFamiglie", ReplyAction:="*")>  _
        Function APPGetBARCODEFamiglieAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutBARCODE", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPPutBARCODE(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content1 As String, ByVal Content2 As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutBARCODE", ReplyAction:="*")>  _
        Function APPPutBARCODEAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content1 As String, ByVal Content2 As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetBARCODE", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPGetBARCODE(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPGetBARCODE", ReplyAction:="*")>  _
        Function APPGetBARCODEAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutTimbratura", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function APPPutTimbratura(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/APPPutTimbratura", ReplyAction:="*")>  _
        Function APPPutTimbraturaAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCli", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSCli(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCli", ReplyAction:="*")>  _
        Function SOSCliAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSCal(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCal", ReplyAction:="*")>  _
        Function SOSCalAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSRep", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSRep(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSRep", ReplyAction:="*")>  _
        Function SOSRepAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCom", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSCom(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCom", ReplyAction:="*")>  _
        Function SOSComAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCRe", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSCRe(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSCRe", ReplyAction:="*")>  _
        Function SOSCReAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSRap", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSRap(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSRap", ReplyAction:="*")>  _
        Function SOSRapAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSSog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function SOSSog(ByVal Password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SOSSog", ReplyAction:="*")>  _
        Function SOSSogAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SyncMobileSoapChannel
        Inherits SyncMobile.SyncMobileSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SyncMobileSoapClient
        Inherits System.ServiceModel.ClientBase(Of SyncMobile.SyncMobileSoap)
        Implements SyncMobile.SyncMobileSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function FineSync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REL As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.FineSync
            Return MyBase.Channel.FineSync(ID, UserID, Password, DUM, REL)
        End Function
        
        Public Function FineSyncAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REL As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.FineSyncAsync
            Return MyBase.Channel.FineSyncAsync(ID, UserID, Password, DUM, REL)
        End Function
        
        Public Function InizioSync(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.InizioSync
            Return MyBase.Channel.InizioSync(ID, UserID, Password)
        End Function
        
        Public Function InizioSyncAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.InizioSyncAsync
            Return MyBase.Channel.InizioSyncAsync(ID, UserID, Password)
        End Function
        
        Public Function APPRichiestaAbilitazione(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPRichiestaAbilitazione
            Return MyBase.Channel.APPRichiestaAbilitazione(ID, UserID, Password)
        End Function
        
        Public Function APPRichiestaAbilitazioneAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPRichiestaAbilitazioneAsync
            Return MyBase.Channel.APPRichiestaAbilitazioneAsync(ID, UserID, Password)
        End Function
        
        Public Function APPGetUtenti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetUtenti
            Return MyBase.Channel.APPGetUtenti(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetUtentiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetUtentiAsync
            Return MyBase.Channel.APPGetUtentiAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClienti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClienti
            Return MyBase.Channel.APPGetRapportiniClienti(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiAsync
            Return MyBase.Channel.APPGetRapportiniClientiAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiSedi(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiSedi
            Return MyBase.Channel.APPGetRapportiniClientiSedi(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiSediAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiSediAsync
            Return MyBase.Channel.APPGetRapportiniClientiSediAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiSediSpese(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiSediSpese
            Return MyBase.Channel.APPGetRapportiniClientiSediSpese(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiSediSpeseAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiSediSpeseAsync
            Return MyBase.Channel.APPGetRapportiniClientiSediSpeseAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiSediSoggetti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiSediSoggetti
            Return MyBase.Channel.APPGetRapportiniClientiSediSoggetti(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniClientiSediSoggettiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiniClientiSediSoggettiAsync
            Return MyBase.Channel.APPGetRapportiniClientiSediSoggettiAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniNoteSpeseTipi(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiniNoteSpeseTipi
            Return MyBase.Channel.APPGetRapportiniNoteSpeseTipi(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniNoteSpeseTipiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiniNoteSpeseTipiAsync
            Return MyBase.Channel.APPGetRapportiniNoteSpeseTipiAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniCommesse(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiniCommesse
            Return MyBase.Channel.APPGetRapportiniCommesse(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiniCommesseAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiniCommesseAsync
            Return MyBase.Channel.APPGetRapportiniCommesseAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapporti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapporti
            Return MyBase.Channel.APPGetRapporti(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiAsync
            Return MyBase.Channel.APPGetRapportiAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPPutRapporti(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPPutRapporti
            Return MyBase.Channel.APPPutRapporti(ID, UserID, Password, DUM, REC, Content, Content1, Content2, Content3, Content4, Content5)
        End Function
        
        Public Function APPPutRapportiAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPPutRapportiAsync
            Return MyBase.Channel.APPPutRapportiAsync(ID, UserID, Password, DUM, REC, Content, Content1, Content2, Content3, Content4, Content5)
        End Function
        
        Public Function APPPutRapportiFromDomino(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPPutRapportiFromDomino
            Return MyBase.Channel.APPPutRapportiFromDomino(ID, UserID, Password, DUM, REC, Content, Content1, Content2, Content3, Content4, Content5)
        End Function
        
        Public Function APPPutRapportiFromDominoAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String, ByVal Content1 As String, ByVal Content2 As String, ByVal Content3 As String, ByVal Content4 As String, ByVal Content5 As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPPutRapportiFromDominoAsync
            Return MyBase.Channel.APPPutRapportiFromDominoAsync(ID, UserID, Password, DUM, REC, Content, Content1, Content2, Content3, Content4, Content5)
        End Function
        
        Public Function APPGetAutorizzazioniTelegram(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetAutorizzazioniTelegram
            Return MyBase.Channel.APPGetAutorizzazioniTelegram(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetAutorizzazioniTelegramAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetAutorizzazioniTelegramAsync
            Return MyBase.Channel.APPGetAutorizzazioniTelegramAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPPutRapportiFromTelegram(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As String Implements SyncMobile.SyncMobileSoap.APPPutRapportiFromTelegram
            Return MyBase.Channel.APPPutRapportiFromTelegram(ID, UserID, Password, DUM, REC, Content)
        End Function
        
        Public Function APPPutRapportiFromTelegramAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As System.Threading.Tasks.Task(Of String) Implements SyncMobile.SyncMobileSoap.APPPutRapportiFromTelegramAsync
            Return MyBase.Channel.APPPutRapportiFromTelegramAsync(ID, UserID, Password, DUM, REC, Content)
        End Function
        
        Public Function APPGetRapportiSpese(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetRapportiSpese
            Return MyBase.Channel.APPGetRapportiSpese(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetRapportiSpeseAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetRapportiSpeseAsync
            Return MyBase.Channel.APPGetRapportiSpeseAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function UploadFirmaSoggetto(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As Boolean Implements SyncMobile.SyncMobileSoap.UploadFirmaSoggetto
            Return MyBase.Channel.UploadFirmaSoggetto(ID, UserID, Password, DUM, REC, Content)
        End Function
        
        Public Function UploadFirmaSoggettoAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content As String) As System.Threading.Tasks.Task(Of Boolean) Implements SyncMobile.SyncMobileSoap.UploadFirmaSoggettoAsync
            Return MyBase.Channel.UploadFirmaSoggettoAsync(ID, UserID, Password, DUM, REC, Content)
        End Function
        
        Public Sub GetDominoData(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) Implements SyncMobile.SyncMobileSoap.GetDominoData
            MyBase.Channel.GetDominoData(ID, UserID, Password, DUM, REC)
        End Sub
        
        Public Function GetDominoDataAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task Implements SyncMobile.SyncMobileSoap.GetDominoDataAsync
            Return MyBase.Channel.GetDominoDataAsync(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function GetDominoDataQuery(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As String Implements SyncMobile.SyncMobileSoap.GetDominoDataQuery
            Return MyBase.Channel.GetDominoDataQuery(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function GetDominoDataQueryAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task(Of String) Implements SyncMobile.SyncMobileSoap.GetDominoDataQueryAsync
            Return MyBase.Channel.GetDominoDataQueryAsync(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function APPGetBARCODEFamiglie(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetBARCODEFamiglie
            Return MyBase.Channel.APPGetBARCODEFamiglie(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPGetBARCODEFamiglieAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetBARCODEFamiglieAsync
            Return MyBase.Channel.APPGetBARCODEFamiglieAsync(ID, UserID, Password, DUM)
        End Function
        
        Public Function APPPutBARCODE(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content1 As String, ByVal Content2 As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPPutBARCODE
            Return MyBase.Channel.APPPutBARCODE(ID, UserID, Password, DUM, REC, Content1, Content2)
        End Function
        
        Public Function APPPutBARCODEAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String, ByVal Content1 As String, ByVal Content2 As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPPutBARCODEAsync
            Return MyBase.Channel.APPPutBARCODEAsync(ID, UserID, Password, DUM, REC, Content1, Content2)
        End Function
        
        Public Function APPGetBARCODE(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPGetBARCODE
            Return MyBase.Channel.APPGetBARCODE(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function APPGetBARCODEAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPGetBARCODEAsync
            Return MyBase.Channel.APPGetBARCODEAsync(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function APPPutTimbratura(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.APPPutTimbratura
            Return MyBase.Channel.APPPutTimbratura(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function APPPutTimbraturaAsync(ByVal ID As String, ByVal UserID As String, ByVal Password As String, ByVal DUM As String, ByVal REC As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.APPPutTimbraturaAsync
            Return MyBase.Channel.APPPutTimbraturaAsync(ID, UserID, Password, DUM, REC)
        End Function
        
        Public Function SOSCli(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSCli
            Return MyBase.Channel.SOSCli(Password)
        End Function
        
        Public Function SOSCliAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSCliAsync
            Return MyBase.Channel.SOSCliAsync(Password)
        End Function
        
        Public Function SOSCal(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSCal
            Return MyBase.Channel.SOSCal(Password)
        End Function
        
        Public Function SOSCalAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSCalAsync
            Return MyBase.Channel.SOSCalAsync(Password)
        End Function
        
        Public Function SOSRep(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSRep
            Return MyBase.Channel.SOSRep(Password)
        End Function
        
        Public Function SOSRepAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSRepAsync
            Return MyBase.Channel.SOSRepAsync(Password)
        End Function
        
        Public Function SOSCom(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSCom
            Return MyBase.Channel.SOSCom(Password)
        End Function
        
        Public Function SOSComAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSComAsync
            Return MyBase.Channel.SOSComAsync(Password)
        End Function
        
        Public Function SOSCRe(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSCRe
            Return MyBase.Channel.SOSCRe(Password)
        End Function
        
        Public Function SOSCReAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSCReAsync
            Return MyBase.Channel.SOSCReAsync(Password)
        End Function
        
        Public Function SOSRap(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSRap
            Return MyBase.Channel.SOSRap(Password)
        End Function
        
        Public Function SOSRapAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSRapAsync
            Return MyBase.Channel.SOSRapAsync(Password)
        End Function
        
        Public Function SOSSog(ByVal Password As String) As System.Data.DataTable Implements SyncMobile.SyncMobileSoap.SOSSog
            Return MyBase.Channel.SOSSog(Password)
        End Function
        
        Public Function SOSSogAsync(ByVal Password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements SyncMobile.SyncMobileSoap.SOSSogAsync
            Return MyBase.Channel.SOSSogAsync(Password)
        End Function
    End Class
End Namespace
